import json
with open('.cache/dashboard_cache.json') as f:
    cache = json.load(f)
daily = cache.get('daily', {})
dates = [d for d in daily if '2026-04-01' <= d <= '2026-04-15']
def s(k): return sum(daily[d].get(k, 0) for d in dates)

print('SHOPIFY')
print(f'  Net Sales:    ${s("net_sales"):>12,.2f}  | Whatagraph: $320,773.14')
print(f'  Orders:       {int(s("orders")):>12,}  | Whatagraph: 4,706')
print()
print('AMAZON ADS  (console: spend $70,192.66 | sales $222,283.66 | impr 15,097,785 | purch 5,253)')
print(f'  Ad Spend:     ${s("amz_ad_spend"):>12,.2f}')
print(f'  Ad Sales:     ${s("amz_ad_sales"):>12,.2f}')
print(f'  Impressions:  {int(s("amz_impressions")):>12,}')
print(f'  Purchases:    {int(s("amz_purchases")):>12,}')
print()
print('AMAZON SC  (SC: $379,075.14)')
print(f'  Gross Sales:  ${s("amz_gross_sales"):>12,.2f}')
print()
print('META  (Whatagraph: spend $58,601 | purch value $134,053 | impr N/A)')
print(f'  Spend:        ${s("meta_spend"):>12,.2f}')
print(f'  Purch Value:  ${s("meta_purchase_value"):>12,.2f}')
print(f'  Impressions:  {int(s("meta_impressions")):>12,}')
print()
print('GOOGLE  (Whatagraph: spend $24,885.49 | conv value $114,548)')
print(f'  Spend:        ${s("google_spend"):>12,.2f}')
print(f'  Conv Value:   ${s("google_conversions_value"):>12,.2f}')
print()
print('BING  (UI: spend $2,676.41 | conv value $10,415.11)')
print(f'  Spend:        ${s("bing_spend"):>12,.2f}')
print(f'  Conv Value:   ${s("bing_conversions_value"):>12,.2f}')
print()
print('REDDIT  (Whatagraph: spend $4,740.40 | purch value $7,264)')
print(f'  Spend:        ${s("reddit_spend"):>12,.2f}')
print(f'  Purch Value:  ${s("reddit_purchase_value"):>12,.2f}')
print()
reach = cache.get('monthly_meta_reach', {}).get('2026-04', 'N/A')
ga4   = cache.get('monthly_ga4', {}).get('2026-04', {})
klav  = cache.get('monthly_klaviyo', {}).get('2026-04', {})
print('MONTHLY MTD  (Whatagraph Apr 1-15: reach 1,233,438 | users 100,717 | sessions 129,270 | emails 1,754,421)')
print(f'  FB Reach:     {reach:>12,}')
print(f'  GA4 Users:    {str(ga4.get("users","N/A")):>12}')
print(f'  GA4 Sessions: {str(ga4.get("sessions","N/A")):>12}')
print(f'  Klaviyo sent: {str(klav.get("emails_sent","N/A")):>12}')
